gameplay:
  # The maximum amount of hunters at any one time.
  max-hunters: 5
  # How many lives does the prey have
  prey-lives: 3
  # Any blocks on this list cannot be placed or broken
  block-blacklist:
    - RESPAWN_ANCHOR
    - BED
    - TNT
  # Which items are blacklisted from being used. Adding flint and steel to this list
  # will mean flint and steel cannot be used UNLESS on obsidian
  item-blacklist:
    - LAVA_BUCKET
    - FLINT_AND_STEEL
  # What spawn range do hunters spawn at in relation to the prey
  hunter-min-spawn-range: 800
  hunter-max-spawn-range: 2500
  # Where are prey spawned after a game is started, format is x, z.
  prey-spawn-location: 0,0
  # The world where the prey will spawn
  prey-spawn-world: 'World'
  # The world where all the lobby is present.
  spawn-world-name: 'World'
  # The interval at which the hunter's/prey's compass is updated with their target's location. This is in seconds
  compass-update-interval: 60
queue:
  # If any prey join that have not played before, automatically teleport them to the given spawn.
  # Practically speaking, if you reset the LuckPerms database, then the plugin will assume that any prey that join
  # will have not played the server before and therefore will teleport them to the spawn.
  auto-teleport-new-prey: true
  # The LuckPerm role which says a player is a 'prey'
  prey-role: 'prey'
  # The LuckPerms roles which gives priority status to Hunters
  priority-roles:
    - supporter
    - friend
  # When a position becomes available, how much time before the confirmation is timed out. This setting is in seconds
  confirm-timeout: 30
  # How much time must past for premium members until they can play as a hunter again. This will read hours as h, or minutes as m
  cooldown: 12h
  # Links used when a player is not a paid subscriber.
  twitch-quick-link: 'https://www.twitch.tv/uriahshorts'
  youtube-quick-link: 'https://www.youtube.com/@uriahshorts'
  